app = "game-server-watcher"
primary_region = "ams"

[env]
  PRIMARY_REGION = "ams"
  DBG = "0"
  DATA_PATH = "/data/"
  REFRESH_TIME_MINUTES = "2"

[mounts]
  source = "gsw_data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    soft_limit = 50
    hard_limit = 60

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"
