name: 🏗 Create cloud app

on:
  workflow_dispatch:

jobs:
  create:
    name: 🛫 Create the app and volume entries
    runs-on: ubuntu-latest

    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: 🛩 Create on fly.io
        run: |
          flyctl apps create ${{ github.repository_owner }}-gsw
          flyctl volumes create gsw_data --region ${{ secrets.FLY_REGION }} --size 1
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
