name: 🏗 Create cloud app

on:
  workflow_dispatch:

jobs:
  create:
    name: 🛫 Create the app and volume entries
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: 🧱 Create fly.io app
        run: flyctl apps create ${{ github.repository_owner }}-gsw --org personal

      - name: 💽 Create fly.io volume
        run: flyctl volumes create gsw_data --size 1 --region ${{ secrets.FLY_REGION }} --app ${{ github.repository_owner }}-gsw --yes
